### ISSUE TITLE
Package Info inventory panel has two vertical scroll bars 

### ISSUE THREAD

**Issue by matt-cahill** [munki/mwa2#17]
Happens when the number of entries exceeds the fixed vertical height of the panel. I assume this would happen on the Manifest panel too but I don't have that many manifests. Potentially the vertical height of the panel should auto size to the vertical space available in the browser window.

<img width="569" alt="screen shot 2016-01-25 at 11 44 19 am" src="https://cloud.githubusercontent.com/assets/2563358/12539506/11ee2248-c359-11e5-9cc7-72e4ba3d3a87.png">

**Comment by gregneagle** [comment]
This looks like the same as issue https://github.com/munki/mwa2/issues/4, which was fixed here: https://github.com/munki/mwa2/commit/230e1de5c42f1cde279b01864ced0a6b83f6799e

Can you do a `git pull` to make sure you are current and look at this again?

**Comment by matt-cahill** [comment]
I was up to date with the master but some locally cached application data was not allowing the fix to show. Opening in a private window/clearing the browser cache fixes this. Apologies about that.

cheers
