### ISSUE TITLE
Package Info linking to wrong file

### ISSUE THREAD

**Issue by vandehey** [munki/mwa2#29]
I have mwa2_demo downloaded and running with run_mwa2.sh on OSX. I'm runnning this against a copy of our production manifest. I'm seeing an issue specific to the Package Info items. I see all of our packages in this view, but when I click on the version to display info on it, a completely different item comes up. For example, when I click on AdobeReader 11.0.10, the pkg info displayed is for Skype. It's almost like they were randomly shuffled. 

When I hover on AdobeReader 11.0.10 I see that the URL that is constructed is pointing at a skype pksinfo file. It's not that everything is shifted by one package or anything, it seems very randomly ordered. Is there any re-indexing that can be done? I've restarted the service, and restarted the server all together. Same result. Is this something that has ever come up?

**Comment by gregneagle** [comment]
I've not seen behavior like that, nor had reports of it.

What happens if you rebuild your catalogs?

**Comment by vandehey** [comment]
Thanks for the quick reply Greg. I rebuilt my catalogs, and everything is groovy. I did not makecatalogs after I copied my repo to my sandbox. Looks like that's all that it took. Thanks again.
