### ISSUE TITLE
Addition to Manifests view.

### ISSUE THREAD

**Issue by dimaui** [munki/mwa2#31]
In the old munkiwebadmin version under "Manifests" there was a column called users which we used to quickly identify the computer- and usernames in the main view.
With mwa2 this information is gone, are there any plans to bring this back?

**Comment by gregneagle** [comment]
No immediate plans, no.

**Comment by hfike** [comment]
@dimaui I used this as well to make things easier for others as well as myself. Made it easy to find a manifests since I use the machine serial number for the manifest name. I'm going to dig into this but wanted to see if you had looked into it any further.
