### ISSUE TITLE
CAS/ADFS integration

### ISSUE THREAD

**Issue by danner26** [munki/mwa2#33]
Hello,

I work at a local university in New Jersey, which we have setup Munki. We use Munki extensively on all of our macs, and we have setup MWA2 for one of our management interfaces. Right now, I have setup a PROD and PPRD system for testing, but we need to find a way to integrate CAS so we can use our auth servers for login. Is this something you are planning on integrating or might be able to help me with?

I was looking at different ways that CAS could be integrated, and I am coming up short in most areas. We are using NGINX for our web proxy on the machine and we are hoping to find a way to integrate CAS into MWA2.

**Comment by vmiller** [comment]
MWA2 is written in Django.  A quick google search reveals several Django modules to support CAS authentication.

**Comment by danner26** [comment]
That isn't the issue here, I found the module and set up a pre production system to test the installation of it, but I am not familiar with Django in the slightest, so I was asking for help implementing it or if it was on a roadmap of some sort. Since I am not familiar with Django, I could spend a few hours dissecting the code and figuring out where configuration and implementation should go, but that would be ultimately unproductive as I have other work to do here.

If I happen to find a way to make it work, I will be happy to submit my code so it could help someone else.

**Comment by danner26** [comment]
Is MWA2 not being developed anymore?

**Comment by gregneagle** [comment]
It currently does what I need, so I haven't needed to make updates to it since last summer. And no-one else has submitted Pull Requests... Make of those facts what you will.

I don't need CA/ADFS integration, so this not something I'd work on. That would most-likely be done at the Django level, and would not really involve any code changes to MWA2.
