### ISSUE TITLE
Wiki setup notes for RHEL / CentOS 7

### ISSUE THREAD

**Issue by wholegroanoats** [munki/mwa2#34]
Hello,

There is a correction required for the wiki setup notes, specifically for the [Apache WSGI Configuration](https://github.com/munki/mwa2/wiki/RHEL7-setup-notes#create-your-apache-config).

The permissions access control lists changed between Apache 2.2 (default on RHEL / CentOS 6) and Apache 2.4 (default on RHEL / CentOS 7). The instructions there currently will work on 6, but not 7. The 7 instructions would require replacing the following lines:

`        Order deny,allow`
`        Allow from all`

With this:

`        Require all granted`

After making this change, I was able to get my instance of mwa2 accessible through Apache 2.4 on CentOS 7.

**Comment by gregneagle** [comment]
The wiki is editable! Please make the needed changes.
