### ISSUE TITLE
Add support for `precache` pkginfo key

### ISSUE THREAD

**Issue by ChefAustin** [munki/mwa2#35]
With the release of Munki v.3.5 came new functionality for the `precache` pkginfo key. MWA2 in its current state does not seem to understand this key. It would be pretty neat if MWA2 were able to offer this up as an option to the user when manipulating a new pkginfo key-value pair.

Note: I might be able to pull off a PR for this, but in case someone had this laying around their fork and could beat me to it... figured I'd throw it out there.

**Comment by gregneagle** [comment]
You can add any key name you like with no code changes to MWA2 right now, then select Boolean.

Or you can switch to the plist view and do it there.

Yes, it would be nice to add more overt support for this and any other new keys MWA2 doesn't currently auto-complete/auto-suggest for you, but it's not a requirement to use `precache` in MWA2.

<img width="792" alt="image" src="https://user-images.githubusercontent.com/700560/53927977-6436b380-403d-11e9-91ef-196f03029ca3.png">

<img width="316" alt="image" src="https://user-images.githubusercontent.com/700560/53928015-76b0ed00-403d-11e9-82c9-a68331da4fd0.png">

**Comment by gregneagle** [comment]
Hint: this is the file to edit if you want to create a PR: https://github.com/munki/mwa2/blob/c0d53eadcb5a7d7a26c396a53284d31497a6ce08/pkgsinfo/static/pkgsinfo/js/pkgsinfo.js#L433-L497

**Comment by ChefAustin** [comment]
(Wow. That was by and large the quickest response I've ever encountered. Bravo. 👏)

Absolutely! We are, in fact, doing just as you suggested and all is running smooth as butter. I think you quite clearly see the value-add of my proposition (in terms of auto-completion/suggestion), so I need not elaborate "the why" on this request any further. 

Additionally, much appreciate the tip! I'll take a gander at it and see if I can get a PR in for ya. 

Thanks for all you do, @gregneagle.
