### ISSUE TITLE
2FA Authntication 

### ISSUE THREAD

**Issue by v0073** [munki/mwa2#43]
You can set up a Munki server on any platform that supports a web server.
we trying to config for 2FA on one login ? Do we configure munki on one login ?

**Comment by gregneagle** [comment]
MunkiWebAdmin2 is a web-based administrative tool for Munki admins. 

It is not a Munki server for use by Munki client machines.

**Comment by gregneagle** [comment]
Implementing 2FA in front of an MWA2 instance is possible but not documented as part of the MWA2 project. Since MWA2 is a Django application, you should look for documentation on implementing 2FA for Django.

**Comment by v0073** [comment]
Thanks for your response  i will search for Django.
