### ISSUE TITLE
Touché

### ISSUE THREAD

**Issue by nwai** [munki/mwa2#45]
Having issue with MWA2 not liking applications with an accent over e. As in Touch**é**.
MWA2 lets users add the app into a manifest, refresh the page and it's pink, add app again, rinse repeat

**Comment by gregneagle** [comment]
I'm going to need a little more than that to replicate and do anything about it.

**Comment by gregneagle** [comment]
After some guessing, I think I understand the issue, which is Unicode-related. There are often multiple ways to represent what visually looks like the same Unicode text:

```
>>> a = b'Touch\xc3\xa9'.decode('utf-8')
>>> b = b'Touche\xcc\x81'.decode('utf-8')
>>> a
'Touché'
>>> b
'Touché'
>>> a == b
False
```

a and b are two different Unicode strings that visually look the same. One way to address this is:

```
>>> import unicodedata
>>> unicodedata.normalize("NFC", a) == unicodedata.normalize("NFC", b)
True
```

This actually also affects Munki itself, and I'm mystified that no-one has surfaced this issue to date. Addressed in Munki here: https://github.com/munki/munki/commit/80bf6d48add04aec498eea690b9a1b21a64a0319

**Comment by gregneagle** [comment]
Thinking about this a bit more, this might also be affected by operating system differences. If MWA2 is running on Linux, it might store Unicode characters non-normalized, or normalized using an alternate format from that used by macOS. This might explain why I haven't gotten a lot of reports for this issue.

**Comment by gregneagle** [comment]
Yes, it's definitely affected by OS.  
MWA2 running on Red Hat Enterprise Linux 7.6:
<img width="720" alt="image" src="https://user-images.githubusercontent.com/700560/95665127-2a277080-0b02-11eb-8a72-cb08d55db24a.png">

MWA2 running on macOS 10.15.6:
<img width="596" alt="image" src="https://user-images.githubusercontent.com/700560/95665146-5cd16900-0b02-11eb-807e-c6ca919465a8.png">

**Comment by gregneagle** [comment]
I think this addresses the issue: https://github.com/munki/mwa2/commit/8e8d9084046ca6a7d1e642a325ad72890db07ae6  
You'll need to pull the changes, and then you might need to activate the virtualenv and do a `python ./mwa2/manage.py collectstatic` depending on how you've configured the webserver portion.

**Comment by nwai** [comment]
Thank you Greg.
Guessing you're not going to need more than that.
Are there no French munk/mwa2 users? Surely if there were someone may have come across this.

Astounded at how your brain must work. Of course unicode chars! Your fix is so much more elegant, I just worked around it by renaming Touché to Touche in Munki Admin.
Your work, and that of all contributors to the Munki solution to managing macOS devices post monolithic imaging is very, very much appreciated.
