### ISSUE TITLE
Package Info wrong

### ISSUE THREAD

**Issue by trekkim** [munki/mwa2#46]
Hi I have issue with MWA2,

suddenly when i click on any of Package info in MWA2 i see wrong Plist info .

for example Adium and i see Slack plist.

any idea what can be reason for that.

But if i will test with MunkiAdmin GUI all good or if i read plist from Adium all looks correct .

thank you
![Screenshot 2020-12-10 at 12 22 29](https://user-images.githubusercontent.com/6920257/101765979-623b3780-3ae2-11eb-93cb-8a8b2fc9d9b4.png)

**Comment by gregneagle** [comment]
If this persists after a page reload, try running `makecatalogs` against the repo.

**Comment by trekkim** [comment]
will try , thx, just curios did you see this before.

**Comment by trekkim** [comment]
All solved , thx Greg for your help.
