### ISSUE TITLE
Running mwa2 in nginx?

### ISSUE THREAD

**Issue by jby** [munki/mwa2#48]
Is it possible to run mwa2 in nginx or is the wsgi-server required?

**Comment by gregneagle** [comment]
If Nginx can run cgis it should be possible. That is the entire amount of knowledge I have on this topic.

**Comment by zakes-it** [comment]
I've got a mwa2 server running on CentOS 8.3 served by nginx. Feel free to reach out on the MacAdmins Slack for config help, username 'zakes'.
