### ISSUE TITLE
Manifest view - manifest name/path truncated to 70 characters

### ISSUE THREAD

**Issue by erikng** [munki/mwa2#7]
If a manifest's full path is over 70 characters, it is truncated.

![70 characters](https://cloud.githubusercontent.com/assets/5685016/12206860/f26013e4-b608-11e5-8683-4e5f8ee83ddb.png)

**Comment by gregneagle** [comment]
How do you think this should be handled? Center truncation? Head truncation? You might be tempted to say "display the whole thing" but what does that do to the rest of the display?

**Comment by gregneagle** [comment]
Better might be a hierarchal tree-view instead of a simple list. I tried one early in development but never found one I liked.

**Comment by erikng** [comment]
A tree view would be nice, especially if by default they were collapsed.

**Comment by gregneagle** [comment]
So now you have a task! Good luck.

**Comment by erikng** [comment]
Looks like it's not actually truncated to just 70 characters. I haven't looked at the bootstrap views, but is it a 2 column view with 1/3 of the width going to the manifest? If so, we may just tweak that value for now.

As it stands, there is quite a bit of wasted space on the editing column.

**Comment by gregneagle** [comment]
"As it stands, there is quite a bit of wasted space on the editing column." Might depend on your screen size, no?  11" MacBookAir vs 27" iMac or 34" external monitor...

**Comment by erikng** [comment]
Yes, but bootstrap shouldn't care. Ideally it should be designed for smaller screens but still expand for larger monitors.

**Comment by gregneagle** [comment]
So poke at the layout and show me one that works!

**Comment by erikng** [comment]
Alright got caught up in something, but I think this looks good.

manifests.html

```
<div class="col-xs-5 col-sm-5 col-md-5 col-lg-5">
<div class='col-xs-7 col-sm-7 col-md-7 col-lg-7'>
```

Super small change. Want a PR?

**Comment by erikng** [comment]
On 1920x1200, this small change gives a significant increase in character limitations if viewed in full screen.

**Comment by erikng** [comment]
Resolved via https://github.com/munki/mwa2/commit/cfaca8fa921a3c9482e0cfeb558026be87a12a93
